# Generated by Django 4.0.4 on 2022-10-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='driver',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='published',
            field=models.BooleanField(),
        ),
    ]
