# Generated by Django 4.0.4 on 2022-10-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='published',
            new_name='created',
        ),
    ]
