# Generated by Django 4.0.1 on 2022-11-22 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('family', '0003_rename_start_family_name'),
        ('users', '0007_alter_users_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='users',
            name='family_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AddField(
            model_name='users',
            name='group_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
