# Generated by Django 4.0.1 on 2022-11-22 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_rename_start_family_name'),
        ('groups', '0001_initial'),
        ('users', '0008_remove_users_serial_number_users_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='family_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
