# Generated by Django 4.0.1 on 2022-11-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('family', '0003_rename_start_family_name'),
        ('users', '0010_remove_users_password_alter_users_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='family_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
