# Generated by Django 4.0.1 on 2022-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_users_family_id_alter_users_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='driver',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
