# Generated by Django 4.0.1 on 2022-12-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_address_alter_groups_name'),
        ('family', '0004_alter_family_name'),
        ('users', '0012_alter_users_driver_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='family_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='family.family'),
        ),
        migrations.AlterField(
            model_name='users',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
