# Generated by Django 4.0.1 on 2023-01-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_users_family_id_alter_users_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='passengers',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
