# Generated by Django 4.0.1 on 2023-01-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_users_passengers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='family_id',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='group_id',
            new_name='group',
        ),
    ]
