# Generated by Django 4.0.4 on 2022-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_buses_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses_user',
            name='busId',
            field=models.CharField(max_length=200),
        ),
    ]
