# Generated by Django 4.0.1 on 2022-11-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.IntegerField(default='')),
                ('user_id', models.IntegerField(default='')),
                ('status', models.BooleanField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
