# Generated by Django 4.0.1 on 2022-11-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_operation_bus_id'),
        ('users', '0010_remove_users_password_alter_users_driver_and_more'),
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='operation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
