# Generated by Django 4.0.1 on 2023-01-12 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_operation_bus_id'),
        ('users', '0013_alter_users_family_id_alter_users_group_id'),
        ('passenger', '0006_alter_passenger_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='operation_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.operation'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
