# Generated by Django 4.0.1 on 2023-01-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0007_alter_passenger_operation_id_alter_passenger_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='operation_id',
            new_name='operation',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='user_id',
            new_name='user',
        ),
    ]
