# Generated by Django 4.0.1 on 2022-11-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='start',
            field=models.CharField(default='', max_length=70),
        ),
    ]
