# Generated by Django 4.0.1 on 2022-11-10 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_family_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='start',
            new_name='name',
        ),
    ]
