# Generated by Django 4.0.1 on 2022-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_rename_start_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
