# Generated by Django 4.0.4 on 2022-11-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default='')),
                ('end', models.BooleanField(default='')),
                ('bus_id', models.IntegerField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
