# Generated by Django 4.0.1 on 2022-11-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_alter_buses_group_id'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='bus_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses'),
        ),
    ]
