# Generated by Django 4.0.1 on 2022-12-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_alter_buses_group_id'),
        ('operation', '0004_alter_operation_bus_id_alter_operation_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='bus_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses', unique=True),
        ),
    ]
