# Generated by Django 4.0.1 on 2023-01-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_operation_bus_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='bus_id',
            new_name='bus',
        ),
    ]
