# Generated by Django 4.0.1 on 2023-01-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_remove_buses_group_id'),
        ('operation', '0006_rename_bus_id_operation_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='bus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start',
            field=models.BooleanField(),
        ),
    ]
