# Generated by Django 4.0.1 on 2023-02-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_alter_operation_bus_alter_operation_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='attendance',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
