# Generated by Django 4.0.4 on 2022-11-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('group_id', models.CharField(default='', max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
