# Generated by Django 4.0.4 on 2022-11-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='group_id',
            field=models.IntegerField(default=''),
        ),
    ]
