# Generated by Django 4.0.1 on 2022-11-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('buses', '0002_alter_buses_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
