# Generated by Django 4.0.1 on 2022-12-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_alter_buses_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
