# Generated by Django 4.0.1 on 2022-12-08 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groups_address_alter_groups_name'),
        ('buses', '0005_alter_buses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='group_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
