# Generated by Django 4.0.1 on 2023-01-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_alter_buses_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='group_id',
        ),
    ]
