# Generated by Django 4.0.1 on 2023-01-17 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0007_remove_buses_group_id'),
        ('groups', '0003_groups_buses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='buses_id',
        ),
        migrations.AddField(
            model_name='groups',
            name='bus_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='buses.buses', unique=True),
        ),
    ]
